### ISSUE TITLE
Error using MATLAB Batch System

### ISSUE THREAD

**Issue by jmechua-itsrdc** [tincala91/COFFEE_BREAK_FDGPET#11]
Hi, I am sharing the run sequence. I just finished spatial normalization then suddenly the MATLABbatch system had an error. 

[error.txt](https://github.com/tincala91/COFFEE_BREAK_FDGPET/files/7271307/error.txt)

Joanna

**Comment by tincala91** [comment]
It is necessary to add the images of the 33 healthy controls available here https://search.kg.ebrains.eu/instances/Dataset/68a61eab-7ba9-47cf-be78-b9addd64bb2f for the script to run. These images have to be added to the MASK_TEMPLATES_HC folder before running the script for the first time.
